### ISSUE TITLE
refetchQueries not working as intented

### ISSUE THREAD

**Issue by PetrKubes97** [KRTirtho/fl-query#23]
The current implementation of refetchQueries refetches all queries NOT specified in the list. Should be reverse.  I think.
```
  /// refetches all the queries matching the passed List of queryKeys
  ///
  /// If an empty list of [queryKeys] is passed then all of the queries
  /// will be refetched
  Future<void> refetchQueries(List<String> queryKeys) async {
    for (final query in cache.queries) {
      if (queryKeys.isNotEmpty && queryKeys.contains(query.queryKey)) continue;
      await query.refetch();
    }
  }
```

**Comment by KRTirtho** [comment]
Oh, this is the old implementation of fl_query. Currently, in v1 this was changed, instead of using `refetch` we have separate `refresh` and `refreshAll` which resolves this confusing behavior
But [fl_query@v1](https://pub.dev/packages/fl_query/versions/1.0.0-alpha.2) is in alpha currently and the jobs API (QueryJob, MutationJob, InfiniteQuery) is still not enabled, so major refactorings will be needed

**Comment by KRTirtho** [comment]
Hey, v1.0.0 was released last week :D

**Comment by KRTirtho** [comment]
@PetrKubes97 please check now. Jobs API has been brought back and now with few refactors, all should just work better than before

**Comment by PetrKubes97** [comment]
@KRTirtho I've migrated the code and seems to work great. 🥳 The only issue I've found was 1:1 replacement of mutateAsync with useMutateJob and scheduleToQueue: true, but wasn't looking too deep into it, maybe a feature, not a bug.
